Add new AmqpSteps for negative cases (2)
aseka-framework/aseka-core pull request #5
Opened 2023-03-10 13:41 UTC by IlyaShp

2023-03-10 14:26 UTC, alex-shendel requested changes

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +                        assertTrue(actualMessage == null, "Queue is not empty: {}", queueName);
Этот ассерт никогда не сработает. Тк ты выше проверил условие в `if`

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check queue {interpolated_string} is empty for {int} s")
Предлагаю переименовать в 
`'check that queue {interpolated_string} is empty for {} sec'`

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check that not exist message in queue {interpolated_string} for {int} s is {file_path}")
Предлагаю чуть изменить на:
"check that message not found in queue {interpolated_string}. message: {file_path}

Отличается чуть от предыдущих, но звучит лучше

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check that not exist message in queue {interpolated_string} for {int} s is:")
Предлагаю чуть изменить на:
"check that message not found in queue {interpolated_string}. message:

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/util/Asserts.java
> +    public static void assertTrue(boolean condition, String message, Object... args) {
Предлагаю удалить его.
Тк уже есть `assertThat(boolean assertion, String message, Object... args)` и он ИМХО читается лучше

"проверить что actualMessage=null" vs "проверить что true actualMessage==null"

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @RetryableStep(defaultRetrySeconds = "2")
Эта аннотация больше не нужна иначе шаг будет всегда проходить

2023-03-10 14:26 UTC, alex-shendel commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @RetryableStep(defaultRetrySeconds = "2")
Нужно удалить RetryableStep

2023-03-16 19:14 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +                        assertTrue(actualMessage == null, "Queue is not empty: {}", queueName);
Поправил

2023-03-16 19:14 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check queue {interpolated_string} is empty for {int} s")
Переименовал

2023-03-16 19:14 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check that not exist message in queue {interpolated_string} for {int} s is {file_path}")
Переименовал

2023-03-16 19:15 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @When("check that not exist message in queue {interpolated_string} for {int} s is:")
Переименовал

2023-03-16 19:15 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/util/Asserts.java
> +    public static void assertTrue(boolean condition, String message, Object... args) {
Отрефакторил

2023-03-16 19:15 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @RetryableStep(defaultRetrySeconds = "2")
Удалил

2023-03-16 19:15 UTC, IlyaShp commented on src/main/java/dev/shendel/aseka/core/steps/AmqpSteps.java
> +    @RetryableStep(defaultRetrySeconds = "2")
Удалил

2023-03-17 00:55 UTC, merged